### ISSUE TITLE
Hash different new line characters

### ISSUE THREAD

**Issue by 592827369** [BlueMountainsIO/ue-plugin-sha256#2]
Hello, I do call the API signature through the blueprint when splicing the data will have a new line exists, I use the plug-in to compare the API provider data has been calculated by a third-party web page structure found that the plug-in string data exists in a new line will be calculated incorrectly, there is a way to fix this? The calculated data is as follows:
POST
/POST

content-type:application/json
host:aiart.tencentcloudapi.com
x-tc-action:imagetoimage

content-type;host;x-tc-action
fc285277ca3451bfc451db5146e9b083ae6d1acc4821e9e2fac20df929fe3203

The correct result should be: 712cf27fba59ac28f42f4104dfea39e269b5a200d72dab1972e1634d0960734f
[SHA256.txt](https://github.com/user-attachments/files/17534054/SHA256.txt)

**Comment by BlueMountainsIO** [comment]
The hash itself is correct but your input is different. Line breaks can either be CRLF (\r\n\) or LF (\n). From the API you probably get LF and on the test website you get CRLF resulting in two different hashes.

Here is an example hashing a string as raw bytes.
![image](https://github.com/user-attachments/assets/56c53664-1f29-4623-bcc9-3cac065ad0d3)

First array is ``POST\nA`` resulting in
```3b754578e5de60d2e0936e7c75ef3afc46f10327a1d0d0b17c33ee27204fa715```
and the second one is ``POST\r\nA`` resulting in 
```341f6c8dde49ed622d07fa7b128306c3384674a08277494f34edcf5f6dc3a6cf```

**Comment by 592827369** [comment]
Yes, but I don't know C++. The format of the API call request data has fixed line breaks and cannot be modified. Is there a way for me to use the blueprint to calculate the correct value based on your plugin? I tried to replace the data line break with \n in the string input node, but it didn't work. I don't know what to do.



---Original---
From: "Blue ***@***.***&gt;
Date: Sun, Oct 27, 2024 22:23 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [BlueMountainsIO/ue-plugin-sha256] String data is miscalculatedfor newlines. (Issue #2)




 
The hash itself is correct but your input is different. Line breaks can either be CRLF (\r\n) or LF (\n). From the API you probably get LF and on the test website you get CRLF resulting in two different hashes.
 
Here is an example hashing a string as raw bytes.
 image.png (view on web)
 
First array is POST\nA resulting in
 3b754578e5de60d2e0936e7c75ef3afc46f10327a1d0d0b17c33ee27204fa715
 and the second one is POST\r\nA resulting in
 341f6c8dde49ed622d07fa7b128306c3384674a08277494f34edcf5f6dc3a6cf

**Comment by BlueMountainsIO** [comment]
This plugin does not provide any string manipulation functions.

**Comment by 592827369** [comment]
The data with line breaks should only be calculated by C++. I tried several plugins and got the same result. I had to give up. Thank you for your reply.



---Original---
From: "Blue ***@***.***&gt;
Date: Sun, Oct 27, 2024 22:23 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [BlueMountainsIO/ue-plugin-sha256] String data is miscalculatedfor newlines. (Issue #2)




 
The hash itself is correct but your input is different. Line breaks can either be CRLF (\r\n) or LF (\n). From the API you probably get LF and on the test website you get CRLF resulting in two different hashes.
 
Here is an example hashing a string as raw bytes.
 image.png (view on web)
 
First array is POST\nA resulting in
 3b754578e5de60d2e0936e7c75ef3afc46f10327a1d0d0b17c33ee27204fa715
 and the second one is POST\r\nA resulting in
 341f6c8dde49ed622d07fa7b128306c3384674a08277494f34edcf5f6dc3a6cf

**Comment by BlueMountainsIO** [comment]
Here I made you a function to convert between the two line breakings

```C++
// MyStringLibrary.h

#pragma once

#include "CoreMinimal.h"
#include "Kismet/BlueprintFunctionLibrary.h"

UCLASS()
class UMyStringLibrary : public UBlueprintFunctionLibrary
{
	GENERATED_BODY()

public:
	UFUNCTION(BlueprintCallable, Category = "String")
	static FString LFToCRLF(const FString& Text);

	UFUNCTION(BlueprintCallable, Category = "String")
	static FString CRLFToLF(const FString& Text);
};

// MyStringLibrary.cpp

#include "MyStringLibrary.h"

FString UMyStringLibrary::LFToCRLF(const FString& Text)
{
	return Text.Replace(TEXT("\n"), TEXT("\r\n"));
}

FString UMyStringLibrary::CRLFToLF(const FString& Text)
{
	return Text.Replace(TEXT("\r\n"), TEXT("\n"));
}
```

**Comment by 592827369** [comment]
It's solved. Thank you so much.
